# Generated by Django 4.0.4 on 2022-05-12 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_id', models.CharField(max_length=10, verbose_name='pick up id')),
                ('dropoff_id', models.CharField(max_length=10, verbose_name='drop off id')),
                ('pickup_date', models.DateField(verbose_name='pick up date')),
                ('dropoff_date', models.DateField(verbose_name='drop off date')),
                ('start_odo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='start odometer')),
                ('end_odo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='end odometer')),
                ('odo_limit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='odometer limit')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='order_amount')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.individualinfo')),
                ('vehicle_id', models.ForeignKey(on_delete=models.SET(999), to='vehicle.vehicleinfo')),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(verbose_name='invoice date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='invoice_amount')),
                ('order_id', models.ForeignKey(on_delete=models.SET(999), to='orders.orderinfo')),
            ],
            options={
                'verbose_name': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.SmallIntegerField(choices=[(1, 'debit card'), (2, 'credit card')], verbose_name='payment method')),
                ('cardno', models.CharField(max_length=16, verbose_name='Card Number')),
                ('pay_date', models.DateField(verbose_name='payment date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='payment_amount')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderinvoice')),
            ],
            options={
                'verbose_name': 'Payment',
            },
        ),
    ]
