# Generated by Django 4.0.4 on 2022-05-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='order_amount'),
        ),
    ]
