# Generated by Django 4.0.4 on 2022-05-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleclass',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='daily rate for vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='extra_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='extra rate for vehicle'),
        ),
    ]
