# Generated by Django 4.0.4 on 2022-05-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicleoffice_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleoffice',
            name='state',
            field=models.CharField(max_length=2, verbose_name='state'),
        ),
    ]
