# Generated by Django 4.0.4 on 2022-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicleoffice_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
