# Generated by Django 4.0.4 on 2022-05-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicleinfo_rented'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfoFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20, verbose_name='make')),
                ('model', models.CharField(max_length=20, verbose_name="vehicle's model")),
                ('make_year', models.DateField(verbose_name='made year')),
                ('VIN', models.CharField(max_length=10, verbose_name='Vehicle_Identification_Number')),
                ('LPN', models.CharField(max_length=10, verbose_name='License Plate Number')),
                ('rented', models.BooleanField(default=False)),
                ('class_type', models.CharField(max_length=50, verbose_name='class type')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='daily rate for vehicle')),
                ('extra_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='extra rate for vehicle')),
                ('office_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicleoffice')),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicleclass')),
            ],
        ),
    ]
